### ISSUE TITLE
Markbot flagging me for something I already have in my code.

### ISSUE THREAD

**Issue by lilbaj** [lilbaj/prefers-accessibility#1]
Hi guys, I hope you are having a good day so far. I got a little bit of a Markbot problem. For some reason, it keeps saying I don't have the code in my main.css when I do (it's even between the styleints). I'm not sure if this had something to do with the .yml file or if I typed something in wrong... please help. 
Edit: the screenshot is cut off a bit but the last part of the styleint is there!!!
<img width="1308" alt="Screen Shot 2020-11-25 at 8 59 10 AM" src="https://user-images.githubusercontent.com/55108804/100237921-910bb800-2efd-11eb-9e38-3600db9dbb2d.png">

@JessJodoin @HannahDelaney

**Comment by HannahDelaney** [comment]
Hey! This stumped me for a hot minute there too, it looked fine.

I managed to find at last though: you've written "perfers" instead of "prefers" in both the media queries. If you adjust that it should pass!

**Comment by lilbaj** [comment]
Wow some part of me knew it was going to come down to a spelling mistake 😅 It worked though, thank you so much!!
